const $ = id => document.getElementById(id);
const fmt = n => Math.floor(n).toLocaleString('ko-KR');
const img = g => `img/wand_${g.toLowerCase()}.png?v=26`;
const grades = {E:1,D:1.2,C:1.5,B:2,A:3,S:5,SS:8,SSS:13};
const gradeClass = g => `grade grade-${g.toLowerCase()}`;
const starText = n => '★'.repeat(n) + '☆'.repeat(Math.max(0,5-n));
const wands = [
 {id:'e1',grade:'E',name:'견습의 나무 지팡이',element:'나무',stars:1,level:0,desc:'초보 마법사가 처음 사용하는 기본 마법봉입니다.'},
 {id:'e2',grade:'E',name:'풀잎 수련 지팡이',element:'풀',stars:1,level:2,desc:'가볍고 다루기 쉬운 수련용 마법봉입니다.'},
 {id:'d1',grade:'D',name:'푸른 물방울 지팡이',element:'물',stars:2,level:4,desc:'차가운 물의 기운을 머금었습니다.'},
 {id:'d2',grade:'D',name:'바람개비 지팡이',element:'바람',stars:2,level:6,desc:'빠른 채굴 리듬을 만들어줍니다.'},
 {id:'c1',grade:'C',name:'달빛 수정 지팡이',element:'달',stars:2,level:8,desc:'은은한 달빛으로 마력을 증폭합니다.'},
 {id:'c2',grade:'C',name:'분홍 별가루 지팡이',element:'별',stars:2,level:10,desc:'별가루가 반짝이는 귀여운 마법봉입니다.'},
 {id:'b1',grade:'B',name:'루비 화염 지팡이',element:'불',stars:3,level:12,desc:'불꽃 이펙트가 강한 공격형 마법봉입니다.'},
 {id:'b2',grade:'B',name:'숲의 정령 지팡이',element:'숲',stars:3,level:14,desc:'정령의 축복으로 안정적인 성장을 돕습니다.'},
 {id:'a1',grade:'A',name:'황금 별빛 지팡이',element:'빛',stars:4,level:16,desc:'골드 획득 감각이 좋아지는 고급 마법봉입니다.'},
 {id:'a2',grade:'A',name:'얼음 왕관 지팡이',element:'얼음',stars:4,level:18,desc:'차가운 왕관 장식이 돋보입니다.'},
 {id:'s1',grade:'S',name:'태양의 마도 지팡이',element:'태양',stars:5,level:21,desc:'강렬한 태양 오라를 두른 희귀 마법봉입니다.'},
 {id:'s2',grade:'S',name:'밤하늘 은하 지팡이',element:'은하',stars:5,level:24,desc:'은하수처럼 반짝이는 프리미엄 마법봉입니다.'},
 {id:'ss1',grade:'SS',name:'천공의 대마법봉',element:'천공',stars:5,level:28,desc:'하늘의 마력을 담은 초희귀 마법봉입니다.'},
 {id:'ss2',grade:'SS',name:'심연의 수정 지팡이',element:'심연',stars:5,level:32,desc:'깊은 심연의 힘을 제어합니다.'},
 {id:'sss1',grade:'SSS',name:'창세의 별 지팡이',element:'창세',stars:5,level:36,desc:'전설 속 창세 마법사가 남긴 지팡이입니다.'},
 {id:'sss2',grade:'SSS',name:'무지개 여왕 지팡이',element:'무지개',stars:5,level:40,desc:'최고 등급의 화려한 상용 게임급 마법봉입니다.'},
 {id:'a3',grade:'A',name:'사탕구름 지팡이',element:'구름',stars:4,level:19,desc:'달콤한 구름 이펙트를 남깁니다.'},
 {id:'s3',grade:'S',name:'오로라 요정 지팡이',element:'오로라',stars:5,level:25,desc:'오로라 빛이 부드럽게 흐릅니다.'},
 {id:'ss3',grade:'SS',name:'별사탕 용사 지팡이',element:'용기',stars:5,level:30,desc:'용사에게 어울리는 밝은 마법봉입니다.'}
];
let state = JSON.parse(localStorage.getItem('mw_v26') || 'null') || {gold:0,gem:100,stone:0,level:0,currentId:'e1',unlocked:['e1'],inventory:[{id:'e1',uid:Date.now()}],options:[],growthStage:1,growthExp:0,autoLevel:0,filter:'ALL'};
function save(){localStorage.setItem('mw_v26',JSON.stringify(state));}
function current(){return wands.find(w=>w.id===state.currentId)||wands[0];}
function enhanceCost(){return Math.floor(100*Math.pow(1.22,state.level));}
function autoCost(){return 500+state.autoLevel*350;}
function successRate(){return Math.max(15,90-state.level*2);}
function clickIncome(){return Math.floor((10+state.level*12)*grades[current().grade]*(1+state.options.length*.08));}
function autoIncome(){return Math.floor(state.autoLevel*(3+state.level)*grades[current().grade]);}
function unlockByLevel(){wands.forEach(w=>{if(state.level>=w.level&&!state.unlocked.includes(w.id))state.unlocked.push(w.id);});}
function setGrade(el,g){el.className=gradeClass(g);el.textContent=g;}
function render(){unlockByLevel();const w=current();$('gold').textContent=fmt(state.gold);$('gem').textContent=fmt(state.gem);$('stone').textContent=fmt(state.stone);$('wandName').textContent=w.name;$('stars').textContent=starText(w.stars);$('wandImg').src=img(w.grade);setGrade($('gradeBadge'),w.grade);$('clickIncome').textContent=fmt(clickIncome());$('autoIncome').textContent=fmt(autoIncome());$('successRate').textContent=successRate();$('enhanceCost').textContent=fmt(enhanceCost());$('enhanceCostMini').textContent=fmt(enhanceCost());$('autoCost').textContent=fmt(autoCost());$('level').textContent=state.level;$('nextLevel').textContent=state.level+1;$('failPenalty').textContent=state.level<10?'없음':state.level<25?'강화 -1':'강화 -2';$('gradeBonusText').textContent='등급 x'+grades[w.grade].toFixed(1);$('gradeBonusInfo').textContent='x'+grades[w.grade].toFixed(1);$('clickBonusBadge').textContent='x'+grades[w.grade].toFixed(1);$('gemDropRate').textContent=(2.5+Math.min(8,state.level*.15)).toFixed(1)+'%';$('optionSummary').textContent=state.options.length?state.options.join(' · '):'없음';$('mainWeaponName').textContent=w.name;$('mainWeaponDesc').textContent=w.desc;$('mainWeaponImg').src=img(w.grade);$('mainWeaponStars').textContent=starText(w.stars);$('mainElement').textContent=w.element;$('mainUnlockState').textContent=state.unlocked.includes(w.id)?'해금됨':'미해금';setGrade($('mainGradeBadge'),w.grade);$('growthStage').textContent=state.growthStage;let need=state.growthStage*5;$('growthNeed').textContent=need;$('growthExp').textContent=state.growthExp;$('growthBar').style.width=Math.min(100,state.growthExp/need*100)+'%';renderCollection();renderOptions();renderInventory();save();}
function msg(t){$('message').textContent=t;}
function floatText(t,x,y){const d=document.createElement('div');d.className='float-text';d.textContent=t;d.style.left=(x||innerWidth/2)+'px';d.style.top=(y||innerHeight/2)+'px';$('effectLayer').appendChild(d);setTimeout(()=>d.remove(),820);}
function mine(e){const gain=clickIncome();state.gold+=gain;if(Math.random()<(.025+Math.min(.08,state.level*.0015))){state.gem++;floatText('+1💎',e?.clientX,e?.clientY-20)}floatText('+'+fmt(gain)+'G',e?.clientX,e?.clientY);msg('마법봉 채굴로 골드를 획득했습니다.');render();}
function enhance(){const cost=enhanceCost();if(state.gold<cost){msg('골드가 부족합니다.');return}state.gold-=cost;if(Math.random()*100<successRate()){state.level++;if(state.level%5===0){state.gem+=10;state.stone+=3;msg('강화 성공! 5단계 보상으로 보석과 마력석을 획득했습니다.');}else msg('강화 성공! 클릭 수익이 증가했습니다.');if(Math.random()<.22){const pool=['클릭 수익 +8%','자동 수익 +8%','보석 드랍 +1%','강화 행운 +3%'];const op=pool[Math.floor(Math.random()*pool.length)];if(!state.options.includes(op))state.options.push(op);}}else{if(state.level>=25)state.level=Math.max(0,state.level-2);else if(state.level>=10)state.level--;msg('강화 실패! 다음 도전을 준비하세요.');}render();}
function buyAuto(){const cost=autoCost();if(state.gold<cost){msg('골드가 부족합니다.');return}state.gold-=cost;state.autoLevel++;state.stone++;msg('마력석 강화 완료! 자동 수익이 증가했습니다.');render();}
function renderCollection(){const wrap=$('collection');wrap.innerHTML='';let list=wands.filter(w=>state.filter==='ALL'||w.grade===state.filter);let unlocked=0;wands.forEach(w=>{if(state.unlocked.includes(w.id))unlocked++});$('bookCount').textContent=`${unlocked} / ${wands.length}`;list.forEach(w=>{const open=state.unlocked.includes(w.id);const card=document.createElement('div');card.className='book-card'+(open?'':' locked');card.innerHTML=`<img src="${img(w.grade)}" alt="${w.name}"><div><h3>${open?w.name:'미등록 마법봉'}</h3><p>${open?w.element+' 속성 · '+starText(w.stars):'+'+w.level+' 달성 또는 뽑기로 해금'}</p></div><strong class="${gradeClass(w.grade)} mini-grade">${w.grade}</strong>`;wrap.appendChild(card);});}
function renderOptions(){const list=$('optionList');list.innerHTML='';if(!state.options.length){list.innerHTML='<div class="empty">보유 옵션 없음<br><small>강화 성공 시 획득</small></div>';return}state.options.forEach(o=>{const d=document.createElement('div');d.className='option-item';d.innerHTML=`<b>${o}</b><span>적용중</span>`;list.appendChild(d);});}
function renderInventory(){const list=$('inventoryList');list.innerHTML='';$('inventoryCount').textContent=state.inventory.length+'개';if(!state.inventory.length){list.innerHTML='<div class="empty">가방이 비어 있습니다.</div>';return}state.inventory.forEach(item=>{const w=wands.find(x=>x.id===item.id)||wands[0];const equipped=item.id===state.currentId;const row=document.createElement('div');row.className='inventory-item';row.innerHTML=`<img src="${img(w.grade)}"><div class="item-info"><h3>${w.name}</h3><p>${w.grade} · ${w.element} 속성 ${equipped?'· 장착중':''}</p></div><div class="item-actions"><button data-equip="${item.uid}">${equipped?'장착중':'꺼내기'}</button><button class="sell" data-sell="${item.uid}" ${equipped?'disabled':''}>판매</button></div>`;list.appendChild(row);});}
function saveCurrent(){state.inventory.push({id:state.currentId,uid:Date.now()+Math.random()});msg('현재 마법봉을 가방에 저장했습니다.');render();}
function summonOne(silent=false){if(state.gem<30){msg('보석이 부족합니다.');return null}state.gem-=30;const r=Math.random()*100;let grade=r<2?'SSS':r<8?'SS':r<20?'S':r<50?(Math.random()<.5?'A':'B'):(['E','D','C'][Math.floor(Math.random()*3)]);const pool=wands.filter(w=>w.grade===grade);const w=pool[Math.floor(Math.random()*pool.length)];if(!state.unlocked.includes(w.id))state.unlocked.push(w.id);state.inventory.push({id:w.id,uid:Date.now()+Math.random()});$('summonResultImg').src=img(w.grade);$('summonResultName').textContent=w.name;$('summonResultDesc').textContent=`${w.grade} 등급 · 가방에 보관됨`;if(!silent)msg(`${w.grade} 등급 ${w.name} 획득!`);return w;}
function train(add){state.growthExp+=add;let need=state.growthStage*5;while(state.growthExp>=need){state.growthExp-=need;state.growthStage++;state.gem+=5;state.stone+=2;need=state.growthStage*5;msg('성장 단계 상승! 보상을 획득했습니다.');}render();}
function switchPanel(id){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.panel===id));window.scrollTo({top:0,behavior:'smooth'});}
document.addEventListener('click',e=>{const equip=e.target.closest('[data-equip]');if(equip){const item=state.inventory.find(i=>String(i.uid)===equip.dataset.equip);if(item){state.currentId=item.id;msg('선택한 마법봉을 장착했습니다.');render();}}const sell=e.target.closest('[data-sell]');if(sell&&!sell.disabled){const i=state.inventory.findIndex(x=>String(x.uid)===sell.dataset.sell);if(i>=0){const w=wands.find(x=>x.id===state.inventory[i].id);state.inventory.splice(i,1);state.gold+=Math.floor(150*grades[w.grade]);state.gem+=Math.max(1,Math.floor(grades[w.grade]));msg('마법봉을 판매했습니다.');render();}}});
$('mineArea').onclick=mine;$('enhanceBtn').onclick=enhance;$('autoBtn').onclick=buyAuto;$('saveBagBtn').onclick=saveCurrent;$('summonOneBtn').onclick=()=>{summonOne();render();};$('summonTenBtn').onclick=()=>{if(state.gem<270){msg('보석이 부족합니다.');return}state.gem-=270;for(let i=0;i<10;i++){state.gem+=30;summonOne(true)}msg('10회 뽑기 완료! 가방을 확인하세요.');render();};$('trainBtn').onclick=()=>train(1);$('feedBtn').onclick=()=>{if(state.stone<5){msg('마력석이 부족합니다.');return}state.stone-=5;train(10)};$('rerollBtn').onclick=()=>{if(state.gem<30){msg('보석이 부족합니다.');return}state.gem-=30;state.options=[];msg('옵션을 재설정했습니다. 강화로 새 옵션을 얻어보세요.');render();};$('sellDupBtn').onclick=()=>{const seen=new Set([state.currentId]);let before=state.inventory.length;state.inventory=state.inventory.filter(i=>{if(seen.has(i.id)){if(i.id===state.currentId)return true;return false}seen.add(i.id);return true});let sold=before-state.inventory.length;state.gold+=sold*180;state.gem+=sold;msg(`중복 ${sold}개 판매 완료`);render();};$('sellAllBtn').onclick=()=>{let kept=state.inventory.filter(i=>i.id===state.currentId);let sold=state.inventory.length-kept.length;state.inventory=kept;state.gold+=sold*160;state.gem+=sold;msg(`판매 가능 마법봉 ${sold}개 판매 완료`);render();};$('resetBtn').onclick=()=>{if(confirm('게임 데이터를 초기화할까요?')){localStorage.removeItem('mw_v26');location.reload();}};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>switchPanel(t.dataset.panel));document.querySelectorAll('.filter').forEach(f=>f.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');state.filter=f.dataset.grade;render();});$('helpBtn').onclick=()=>$('helpModal').classList.add('show');$('helpCloseBtn').onclick=$('helpCloseBottomBtn').onclick=$('helpBackdrop').onclick=()=>$('helpModal').classList.remove('show');setInterval(()=>{let gain=autoIncome();if(gain>0){state.gold+=gain;render();}},1000);render();
